### ISSUE TITLE
Wifi

### ISSUE THREAD

**Issue by YoYoZ** [broadcomCM/android_device_samsung_cooperve#1]
Wifi not working

**Comment by bieltura** [comment]
Wifi is woring first time, then when you stop it and run it again fails, AFAIK, kernel problem, logcat:

D/WifiStateTracker( 1519): Disabling interface
D/WifiHW  ( 1519): Unable to unload driver module "dhd": No such file or directory #Error while turning OFF
E/WifiService( 1519): Failed to unload Wi-Fi driver. #Error for turning OFF
D/Smack   ( 2058): [XMPPConn] close connection, notifyClosed=false
D/SettingsAppWidgetProvider( 2260): Widget is from a previous version... Let's update
D/SettingsAppWidgetProvider( 2260): No instances yet... Wait for at least one instance to exist before adding global settings
D/dalvikvm( 1519): GC_CONCURRENT freed 557K, 50% free 5353K/10503K, external 2416K/2524K, paused 5ms+21ms
W/Smack/Packet( 2058): notify conn break (IOEx), close connection
D/SettingsAppWidgetProvider( 2260): Widget is from a previous version... Let's update
D/SettingsAppWidgetProvider( 2260): No instances yet... Wait for at least one instance to exist before adding global settings
E/WifiService( 1519): Failed to load Wi-Fi driver. #Failed to load again after the bad turning off
D/SettingsAppWidgetProvider( 2260): Widget is from a previous version... Let's update
D/SettingsAppWidgetProvider( 2260): No instances yet... Wait for at least one instance to exist before adding global settings
D/SettingsAppWidgetProvider( 2260): Widget is from a previous version... Let's update
D/SettingsAppWidgetProvider( 2260): No instances yet... Wait for at least one instance to exist before adding global settings
E/WifiService( 1519): Failed to load Wi-Fi driver. # Another try and same...

**Comment by YoYoZ** [comment]
You should check the foldet for a driver. it, easy to brake up while porting driver.

**Comment by bieltura** [comment]
Fixed on BETA 1 :D, closed.

**Comment by rqmok** [comment]
How to fix this problem?
