### ISSUE TITLE
Flashlight

### ISSUE THREAD

**Issue by bieltura** [broadcomCM/android_device_samsung_cooperve#10]
flashlight not detected, logcat:

D/TorchRoot( 1980): Starting torch
W/dalvikvm( 1980): threadid=9: thread exiting with uncaught exception (group=0x40018560)
E/AndroidRuntime( 1980): FATAL EXCEPTION: Timer-0
E/AndroidRuntime( 1980): java.lang.RuntimeException: Can't open flash device
E/AndroidRuntime( 1980):    at net.cactii.flash2.FlashDevice.setFlashMode(FlashDevice.java:126)
E/AndroidRuntime( 1980):    at net.cactii.flash2.TorchService$2.run(TorchService.java:57)
E/AndroidRuntime( 1980):    at java.util.Timer$TimerImpl.run(Timer.java:284)
E/AndroidRuntime( 1980): Caused by: java.io.FileNotFoundException: /sys/class/leds/flashlight/brightness (No such file or directory)
E/AndroidRuntime( 1980):    at org.apache.harmony.luni.platform.OSFileSystem.open(Native Method)
E/AndroidRuntime( 1980):    at dalvik.system.BlockGuard$WrappedFileSystem.open(BlockGuard.java:232)
E/AndroidRuntime( 1980):    at java.io.FileOutputStream.<init>(FileOutputStream.java:94)
E/AndroidRuntime( 1980):    at java.io.FileOutputStream.<init>(FileOutputStream.java:66)
E/AndroidRuntime( 1980):    at java.io.FileWriter.<init>(FileWriter.java:80)
E/AndroidRuntime( 1980):    at net.cactii.flash2.FlashDevice.setFlashMode(FlashDevice.java:115)
E/AndroidRuntime( 1980):    ... 2 more
D/SettingsAppWidgetProvider( 1745): Widget is from a previous version... Let's update
D/SettingsAppWidgetProvider( 1745): No instances yet... Wait for at least one instance to exist before adding global settings
W/ActivityManager( 1510):   Force finishing activity net.cactii.flash2/.MainActivity

**Comment by YoYoZ** [comment]
Actually, this is easy to fix. Brightness file for flashlight is located in the same place, where touch keys file is.

**Comment by bieltura** [comment]
CAn you link me where please?

**Comment by YoYoZ** [comment]
In stock firmware it's in /sys/devices/platform.
Search for it in CM

**Comment by Qeemi** [comment]
Is it in "/sys/devices/platform/bcm21553-leds/leds/button-backlight/brightness" ????????????

**Comment by bieltura** [comment]
hm... Will build with this path... and comment results here

**Comment by YoYoZ** [comment]
Guys, that path is clearly button backlight. it should be near, somethere..

**Comment by Qeemi** [comment]
/sys/class/leds/??????????

OR

sys/devices/platform/aat1401-backlight.0/backlight/aat1401-backlight/brightness           <----------------------------- :+1:  For me it is the right path,but like bieltv.3 said,kernel needs adjustments

**Comment by bieltura** [comment]
Fixed on Beta 4
