### ISSUE TITLE
Signal Bars

### ISSUE THREAD

**Issue by bieltura** [broadcomCM/android_device_samsung_cooperve#11]
Signals bar not working, RIL works but signal bars don't, I can't test it because my phone is breaked in RIL part, as it was donated to me :P

**Comment by spacecaker** [comment]
u still havent tried my ril ? :P xD

**Comment by bieltura** [comment]
Nope sorry bussy with other weird things, btw, why I can't see issues when I click on issues? xD

**Comment by spacecaker** [comment]
because it mightbe a big isseu if u press on the isseus button 
:p

**Comment by bieltura** [comment]
Any idea why cooperve is the only device withoutnRIL bars working?

**Comment by spacecaker** [comment]
can be because of the proprietary ril lib ? 
maybe this one needs to be changes with the propritary ril libs of totoro ( Y )

**Comment by bieltura** [comment]
Will try it :P On exams now, while you come from your holidays ;)

**Comment by spacecaker** [comment]
haha yeah :P just came back
had my exams the week before i left to vacation

**Comment by spacecaker** [comment]
This has been fixed

**Comment by bieltura** [comment]
I don't wt to close anything since the release of the fix ;)

**Comment by spacecaker** [comment]
Ok ;)

**Comment by spacecaker** [comment]
oh sorry damn pressed on wrong button

**Comment by bieltura** [comment]
Solved on RC1
