### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by YoYoZ** [broadcomCM/android_device_samsung_cooperve#2]
Bluetooth not working

**Comment by bieltura** [comment]
LOGCAT:

D/BluetoothService( 1499): Bluetooth state 10 -> 11
V/BluetoothEventRedirector( 1592): Received android.bluetooth.adapter.action.STATE_CHANGED
I/bluedroid( 1499): Starting hciattach daemon
E/bluedroid( 1499): Failed to create bluetooth hci socket: Address family not supported by protocol (97)
D/BluetoothService( 1499): Bluetooth state 11 -> 10
D/SettingsAppWidgetProvider( 1592): Widget is from a previous version... Let's update
D/SettingsAppWidgetProvider( 1592): No instances yet... Wait for at least one instance to exist before adding global settings
V/BluetoothEventRedirector( 1592): Received android.bluetooth.adapter.action.STATE_CHANGED
I/ActivityManager( 1499): Start proc com.android.bluetooth for broadcast com.android.bluetooth/.opp.BluetoothOppReceiver: pid=2411 uid=10039 gids={3003, 3002, 3001, 1015}
D/dalvikvm( 1331): GC_EXPLICIT freed 11K, 51% free 2670K/5379K, external 0K/0K, paused 155ms
D/dalvikvm( 1499): GC_CONCURRENT freed 859K, 46% free 4934K/9095K, external 2407K/2479K, paused 5ms+45ms
D/szipinf ( 2411): Initializing inflate state
D/szipinf ( 2411): Initializing inflate state
I/ActivityThread( 2411): Pub com.android.bluetooth.opp: com.android.bluetooth.opp.BluetoothOppProvider
D/dalvikvm( 1331): GC_EXPLICIT freed <1K, 51% free 2670K/5379K, external 0K/0K, paused 121ms
V/BluetoothMasReceiver( 2411): BluetoothMasReceiver onReceive :android.bluetooth.adapter.action.STATE_CHANGED
E/BluetoothMasReceiver( 2411): BluetoothMasReceiver onReceive :android.bluetooth.adapter.action.STATE_CHANGED
D/BluetoothMasReceiver( 2411): Bluetooth STATE CHANGED to 11
D/SettingsAppWidgetProvider( 1592): Widget is from a previous version... Let's update
D/SettingsAppWidgetProvider( 1592): No instances yet... Wait for at least one instance to exist before adding global settings
D/dalvikvm( 1331): GC_EXPLICIT freed <1K, 51% free 2670K/5379K, external 0K/0K, paused 113ms
V/BluetoothMasReceiver( 2411): BluetoothMasReceiver onReceive :android.bluetooth.adapter.action.STATE_CHANGED
E/BluetoothMasReceiver( 2411): BluetoothMasReceiver onReceive :android.bluetooth.adapter.action.STATE_CHANGED
D/BluetoothMasReceiver( 2411): Bluetooth STATE CHANGED to 10
D/dalvikvm( 1782): GC_EXPLICIT freed 70K, 50% free 2690K/5379K, external 0K/0K, paused 38ms

**Comment by bieltura** [comment]
Solved on RC1
