### ISSUE TITLE
GPS

### ISSUE THREAD

**Issue by YoYoZ** [broadcomCM/android_device_samsung_cooperve#3]
GPS not working as well.

**Comment by spacecaker** [comment]
tried using GPS confg from original Ace Cm7 ?

**Comment by YoYoZ** [comment]
Does it need to be compiled?

**Comment by spacecaker** [comment]
no you can try to copy its gps.conf files 
or merge the one of Cm7 ace source

**Comment by bieltura** [comment]
I think it is working, actually network location works, will test more, but I think it is working.
