### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by YoYoZ** [broadcomCM/android_device_samsung_cooperve#4]
Sound is not working.

**Comment by bieltura** [comment]
Audio works afsik in alpha 2 right?

**Comment by YoYoZ** [comment]
No idea. By Audio means both headphones and both of the speakers?

**Comment by bieltura** [comment]
Audio works fine on Alpha 3, Closed

**Comment by YoYoZ** [comment]
Sound in headphones is not working. Reopen, please.
